version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=foyer_db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  app-foyer:
    depends_on:
      - mysqldb
    image: nourhenemdimagh/tp_foyer:1.0.0
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: | 
        {
          "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/timesheet_db?createDatabaseIfNotExist=true",
          "spring.datasource.username" : "root",
          "spring.datasource.password" : null,
          "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQLDialect",
          "spring.jpa.hibernate.ddl-auto" : "update"
        }
    stdin_open: true
    tty: true

volumes:
  db: