apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytix-deployment
  labels:
    app: analytix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytix
  template:
    metadata:
      labels:
        app: analytix
    spec:
      nodeSelector:
        kubernetes.io/hostname: ch01-srv12
      containers:
        - name: analytix-container
          image: 10.200.0.21:5000/analytix-snapshot/test:1.0.1
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: ""
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://localhost:4317
            - name: OTEL_SERVICE_NAME
              value: analytix-app
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:latest
          args: ["--config=/etc/otel-collector-config.yaml"]
          volumeMounts:
            - name: otel-config
              mountPath: /etc
      volumes:
        - name: otel-config
          configMap:
            name: otel-config
