apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytix-deployment
  namespace: analytix
  labels:
    app: analytix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analytix
  template:
    metadata:
      labels:
        app: analytix
    spec:
      nodeSelector:
        kubernetes.io/hostname: ch01-srv12
      containers:
        - name: analytix-container
          image: docker.registry.local:5000/analytix-snapshot/test:1.0.2
          ports:
            - containerPort: 8082
          env:
            # --- MySQL (svc in same namespace)
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysqldb:3306/foyer_db?createDatabaseIfNotExist=true
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: MANAGEMENT_METRICS_BINDERS_SYSTEM_ENABLED
              value: "false"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-root-secret
                  key: MYSQL_ROOT_PASSWORD
      # Removed OpenTelemetry sidecar and related volumes
