apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv              # <- important pour lier au PV ci-dessus
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
