apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:                         # Pour test local ou VM (ne pas utiliser en prod)
    path: /data/mysql               # Doit exister sur le nœud ch01-srv11
  persistentVolumeReclaimPolicy: Retain
