apiVersion: v1
kind: Service
metadata:
  name: analytix-service
spec:
  selector:
    app: analytix
  type: LoadBalancer
  loadBalancerIP: 10.200.0.27
  ports:
    - protocol: TCP
      port: 8066
      targetPort: 8082